export const queryKeys = {
	session: () => ["session"] as const,
	dishes: () => ["dishes"] as const,
	ingredients: () => ["ingredients"] as const,
	suppliers: () => ["suppliers"] as const,
	inventoryStock: () => ["inventory", "stock"] as const,
	inventoryExpiring: () => ["inventory", "expiring"] as const,
	prepEntries: (serviceDate: string) => ["prep-entries", serviceDate] as const,
	reusePending: () => ["reuse-pending"] as const,
	leftovers: (serviceDate: string) => ["leftovers", serviceDate] as const,
	dispositionSuggestion: (leftoverId: string) => ["leftovers", "suggestion", leftoverId] as const,
	listings: () => ["listings"] as const,
	dashboard: (from: string, to: string) => ["dashboard", from, to] as const,
	marketBrowse: () => ["market", "browse"] as const,
	marketMine: () => ["market", "mine"] as const,
	marketPickups: () => ["market", "pickups"] as const,
	analyticsWaste: (from: string, to: string, grain: string) =>
		["analytics", "waste", from, to, grain] as const,
	analyticsRecovery: (from: string, to: string, grain: string) =>
		["analytics", "recovery", from, to, grain] as const,
	analyticsDishes: (from: string, to: string) => ["analytics", "dishes", from, to] as const,
	analyticsForecasts: (from: string, to: string) => ["analytics", "forecasts", from, to] as const,
	insights: () => ["insights"] as const,
	reports: () => ["reports"] as const,
	team: () => ["team"] as const,
	tenant: () => ["tenant"] as const,
	restaurant: () => ["restaurant"] as const,
	ngo: () => ["ngo"] as const,
	adminTenants: () => ["admin", "tenants"] as const,
	adminAnalytics: () => ["admin", "analytics"] as const,
	notificationPreferences: () => ["notification-preferences"] as const,
}
