export const ERROR_CODES = {
	VALIDATION_FAILED: 422,
	AUTH_INVALID_CREDENTIALS: 401,
	AUTH_TOKEN_EXPIRED: 401,
	AUTH_REFRESH_REUSED: 401,
	AUTH_FORBIDDEN: 403,
	TENANT_TYPE_MISMATCH: 403,
	RESOURCE_NOT_FOUND: 404,
	IDEMPOTENCY_KEY_CONFLICT: 409,
	LISTING_ALREADY_CLAIMED: 409,
	LISTING_NOT_OPEN: 409,
	LISTING_OUT_OF_RANGE: 403,
	DISPOSITION_ALREADY_DECIDED: 409,
	DISPOSITION_SPLIT_MISMATCH: 422,
	LEFTOVER_PAST_SAFE_UNTIL: 422,
	INSUFFICIENT_STOCK: 422,
	REUSE_EXCEEDS_RETAIN: 422,
	RATE_LIMITED: 429,
	AI_UNAVAILABLE: 503,
	INTERNAL: 500,
} as const

export type ErrorCode = keyof typeof ERROR_CODES

export const statusForCode = (code: ErrorCode): number => ERROR_CODES[code]
